version: '3'

services:
  nginx:
    image: nginx:1.27
    container_name: cbioportal-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./config/nginx.conf:/etc/nginx/conf.d/cbioportal.conf:ro
      - /etc/ssl/cbioportal:/etc/ssl/cbioportal:ro
    depends_on:
      - cbioportal
    networks:
      - cbio-net

  cbioportal:
    restart: unless-stopped
    image: ${DOCKER_IMAGE_CBIOPORTAL}
    container_name: cbioportal-container
    environment:
      SHOW_DEBUG_INFO: "true"
      PORTAL_HOME: "/cbioportal-webapp"
    volumes:
     - ./study:/study/
     - ${APPLICATION_PROPERTIES_PATH:-./config/application.properties}:/cbioportal-webapp/application.properties:ro
     - ./config/saml-signing.crt:/cbioportal-webapp/saml-signing.crt:ro
     - ./config/saml-signing.key:/cbioportal-webapp/saml-signing.key:ro
    depends_on:
     - cbioportal-database
     - cbioportal-session
    networks:
     - cbio-net
    command: /bin/sh -c "java -Xms2g -Xmx4g -cp '/cbioportal-webapp:/cbioportal-webapp/lib/*' org.cbioportal.PortalApplication --spring.config.location=cbioportal-webapp/application.properties --authenticate=saml --session.service.url=http://cbioportal-session:5001/api/sessions/my_portal/ --clickhouse_mode=$${APP_CLICKHOUSE_MODE:-false} --spring.profiles.active=$${APP_SPRING_PROFILE:-default}"
  cbioportal-database:
    restart: unless-stopped
    image: ${DOCKER_IMAGE_MYSQL}
    container_name: cbioportal-database-container
    environment:
      MYSQL_DATABASE: ${DB_MYSQL_DB_NAME}
      MYSQL_USER: ${DB_MYSQL_USERNAME}
      MYSQL_PASSWORD: ${DB_MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${DB_MYSQL_PASSWORD}
    volumes:
     - ./data/cgds.sql:/docker-entrypoint-initdb.d/cgds.sql:ro
     - ./data/seed.sql.gz:/docker-entrypoint-initdb.d/seed.sql.gz:ro
     - cbioportal_mysql_data:/var/lib/mysql
    networks:
     - cbio-net
    command: --local-infile=1
    healthcheck:
      test: [ "CMD-SHELL", "mysqladmin ping -h localhost -u $$MYSQL_USER -p$$MYSQL_PASSWORD" ]
      interval: 10s
      timeout: 3s
      retries: 300
      start_period: 3m
  cbioportal-session:
    restart: unless-stopped
    image: ${DOCKER_IMAGE_SESSION_SERVICE}
    container_name: cbioportal-session-container
    environment:
      SERVER_PORT: 5001
      JAVA_OPTS: -Dspring.data.mongodb.uri=mongodb://cbioportal-session-database:27017/session-service
    depends_on:
      - cbioportal-session-database
    networks:
      - cbio-net
  cbioportal-session-database:
    restart: unless-stopped
    image: mongo:4.2
    container_name: cbioportal-session-database-container
    environment:
      MONGO_INITDB_DATABASE: session_service
    volumes:
      - cbioportal_mongo_data:/data/db
    networks:
      - cbio-net

  keycloak:
    container_name: cbiokc
    image: quay.io/keycloak/keycloak:16.1.1
    restart: unless-stopped
    depends_on:
      - keycloak-database
    environment:
      DB_VENDOR: mysql
      DB_ADDR: keycloak-database
      DB_USER: keycloak
      DB_PASSWORD: ${KC_DB_PASSWORD:-MassGeneralHospital@2025!}
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: ${KC_ADMIN_PASSWORD:-MassGeneralHospital@2025!}
      PROXY_ADDRESS_FORWARDING: "true"
      KEYCLOAK_FRONTEND_URL: https://cbioportal.mgb.org/auth
      JAVA_OPTS: "-Xmx384m"
    networks:
      - cbio-net
  keycloak-database:
    container_name: kcdb
    image: mysql:5.7
    restart: unless-stopped
    volumes:
      - keycloak_mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${KC_DB_PASSWORD:-MassGeneralHospital@2025!}
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: ${KC_DB_PASSWORD:-MassGeneralHospital@2025!}
      MYSQL_DATABASE: keycloak
    command: --ssl=0 --lower_case_table_names=1
    networks:
      - cbio-net

networks:
  cbio-net:

volumes:
  cbioportal_mysql_data:
  cbioportal_mongo_data:
  keycloak_mysql_data:
