version: '3'

services:
  cbioportal:
    environment:
      APP_CLICKHOUSE_MODE: true
      APP_SPRING_PROFILE: clickhouse
    depends_on: !override
      - cbioportal-session
    entrypoint: []
  cbioportal-database:
    deploy:
      replicas: 0