services:
  cbioportal:
    depends_on:
      - redis-session
      - redis-persistence-master
      - redis-persistence-replica
  redis-session:
    image: ${DOCKER_IMAGE_REDIS}
    container_name: redis-session
    command: >
      --requirepass ${APP_REDIS_PASSWORD}
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_MAXMEMORY=8gb
      - REDIS_MAXMEMORY_POLICY=volatile-ttl
      - REDIS_DISABLE_COMMANDS=CONFIG,SHUTDOWN
    ports:
      - "${APP_REDIS_SESSION_PORT}:6379"
    volumes:
      - redis-session-data:/bitnami/redis/data
    networks:
      - cbio-net
    restart: unless-stopped
  redis-persistence-master:
    image: ${DOCKER_IMAGE_REDIS}
    container_name: redis-persistence-master
    command: >
      --requirepass ${APP_REDIS_PASSWORD}
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_REPLICATION_MODE=master
      - REDIS_MAXMEMORY=8gb
      - REDIS_MAXMEMORY_POLICY=volatile-ttl
      - REDIS_DISABLE_COMMANDS=CONFIG,SHUTDOWN
    ports:
      - "${APP_REDIS_PERSISTENCE_MASTER_PORT}:6379"
    volumes:
      - redis-persistence-master-data:/bitnami/redis/data
    networks:
      - cbio-net
    restart: unless-stopped
  redis-persistence-replica:
    image: ${DOCKER_IMAGE_REDIS}
    container_name: redis-persistence-replica
    command: >
      --requirepass ${APP_REDIS_PASSWORD}
    environment:
      - ALLOW_EMPTY_PASSWORD=no
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-persistence-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - REDIS_MASTER_PASSWORD=${APP_REDIS_PASSWORD}
      - REDIS_MAXMEMORY=8gb
      - REDIS_MAXMEMORY_POLICY=volatile-ttl
      - REDIS_DISABLE_COMMANDS=CONFIG,SHUTDOWN
    ports:
      - "${APP_REDIS_PERSISTENCE_REPLICA_PORT}:6379"
    volumes:
      - redis-persistence-replica-data:/bitnami/redis/data
    networks:
      - cbio-net
    depends_on:
      - redis-persistence-master
    restart: unless-stopped
volumes:
  redis-session-data:
  redis-persistence-master-data:
  redis-persistence-replica-data: